
project_id = "vlttatulvodsubdqyzrc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = false

[functions]
[functions.arbitrage-bot-control]
verify_jwt = true
[functions.frontrun-bot-control]
verify_jwt = true
[functions.liquidation-bot-control]
verify_jwt = true
[functions.profiter-one-bot-control]
verify_jwt = true
[functions.profiter-two-bot-control]
verify_jwt = true
[functions.sandwich-bot-control]
verify_jwt = true
