
project_id = "vlttatulvodsubdqyzrc"

[functions.arbitrage-bot-control]
verify_jwt = false

[functions.profiter-one-bot-control]
verify_jwt = false

[functions.profiter-two-bot-control]
verify_jwt = false

[functions.liquidation-bot-control]
verify_jwt = false

[functions.frontrun-bot-control]
verify_jwt = false

[functions.sandwich-bot-control]
verify_jwt = false
