// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlttatulvodsubdqyzrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsdHRhdHVsdm9kc3ViZHF5enJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDc5NjgsImV4cCI6MjA2MjI4Mzk2OH0.1PMataPhT1aiJ-TRR8htbklQFQrL8xluJ3dv3pxo0gQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);